[template.environment]
  DATA = "[\"Lorenzo0111\"]"
  NEXT_PUBLIC_SUPABASE_URL = "Your supabase url"
  NEXT_PUBLIC_SUPABASE_ANON_KEY = "Your supabase anon key"
  SUPABASE_SECRET = "Your supabase secret"
  NEXT_PUBLIC_AUTH_METHOD = "discord"