[template.environment]
  DATA = "Your array of users (e.g [\"Lorenzo0111\"])"
  NEXT_PUBLIC_SUPABASE_URL = "Supabase url"
  NEXT_PUBLIC_SUPABASE_ANON_KEY = "Supabase anon key"
  SUPABASE_SECRET = "Supabase secret key"
  NEXT_PUBLIC_AUTH_METHOD = "Authentication method (e.g Discord)"